import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
import io

def generate_pdf_report(mode="Summary", data_summary=None, plot_images=None):
    """
    Standard PDF Reporting Module for Technology Implementation Program.
    :param mode: "Summary" for full dataset overview, "Snapshot" for current view.
    :param data_summary: Dictionary containing stats (mean, Cpk, etc).
    :param plot_images: List of byte-streams for Plotly figures.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    # Title
    title = Paragraph(f"<b>Diagnostic Report: {mode} Mode</b>", styles['Title'])
    elements.append(title)
    elements.append(Spacer(1, 12))

    if mode == "Summary" and data_summary is not None:
        elements.append(Paragraph("<b>Machine Performance Summary</b>", styles['Heading2']))
        
        # Create a table of standard XPDS metrics (Z-Scores, Counts, etc)
        table_data = [["Metric", "Value"]]
        for key, value in data_summary.items():
            table_data.append([key, str(value)])
        
        t = Table(table_data, colWidths=[200, 200])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 24))

    # Add Captured Snapshots
    if plot_images:
        elements.append(Paragraph("<b>Visual Diagnostics</b>", styles['Heading2']))
        for img_data in plot_images:
            # ReportLab requires a file-like object or path
            img = Image(io.BytesIO(img_data), width=400, height=300)
            elements.append(img)
            elements.append(Spacer(1, 12))

    # Footer
    elements.append(Spacer(1, 48))
    elements.append(Paragraph("<i>Generated by XPDS Diagnostic Engine v1.3</i>", styles['Italic']))

    doc.build(elements)
    buffer.seek(0)
    return buffer

def capture_plotly_snapshot(fig):
    """
    Converts an interactive Plotly figure into a static PNG for the PDF.
    Requires kaleido==0.2.1 as specified in requirements.txt.
    """
    return fig.to_image(format="png", engine="kaleido")
